### ISSUE TITLE
Héritage des configurations de composants

### ISSUE THREAD

**Issue by Nyxis** [Synapse-Cmf/synapse-cmf#46]
Implémenter une alternative aux références yml :
```yml
synapse_cmf:
    components:
        text: &text_component
            form: Synapse\Cmf\Bundle\Form\Type\Component\TextType
            controller: SynapseCmfBundle:TextComponent:render
            template_path: SynapseCmfBundle:Component:text.html.twig
        banner:
            <<: *text_component
```
Sous la forme :
```yml
synapse_cmf:
    components:
        banner:
            extends: text
```
